ci: Plugins depend on generated `nodeids.h`
Sometimes travis failed with
```
/home/travis/build/open62541/open62541/build/src_generated/open62541/nodeids.h:6:0: error: unterminated #ifndef

 #ifndef UA_NODEIDS_NS0_H_

 ^
```
if the plugins object was created before namespace generation finished.