Fix all the cppcheck warnings and enable travis fail on cppcheck error
Fixes the following issues:

plugins/networklayer_udp.c(174): style (unsignedLessThanZero): Checking if unsigned variable 'length' is less than zero.
plugins/networklayer_tcp.c(291): style (unreadVariable): Variable 'layer' is assigned a value that is never used.
src/server/ua_services_attribute.c(13): style (variableScope): The scope of the variable 'c' can be reduced.
src/server/ua_server_worker.c(552): style (unreadVariable): Variable 'mlw' is assigned a value that is never used.
src/server/ua_services_view.c(262): style (unsignedLessThanZero): Checking if unsigned variable 'referencesSize' is less than zero.
src/server/ua_services_view.c(273): style (unsignedLessThanZero): Checking if unsigned variable 'referencesSize' is less than zero.
src/ua_types.c(544): error (memleak): Memory leak: new
src/ua_types.c(547): error (memleak): Memory leak: new
src/ua_types_encoding_binary.c(278): style (duplicateExpression): Same expression on both sides of '/'.
src/ua_types_encoding_binary.c(311): style (duplicateExpression): Same expression on both sides of '/'.
src/ua_types_encoding_binary.c(49): error (arrayIndexOutOfBounds): Array 'buf[4]' accessed at index 4, which is out of bounds.
src/ua_types_encoding_binary.c(49): error (arrayIndexOutOfBounds): Array 'buf[4]' accessed at index 5, which is out of bounds.
src/ua_types_encoding_binary.c(50): error (arrayIndexOutOfBounds): Array 'buf[4]' accessed at index 6, which is out of bounds.
src/ua_types_encoding_binary.c(50): error (arrayIndexOutOfBounds): Array 'buf[4]' accessed at index 7, which is out of bounds.
src/ua_types_encoding_binary.c(326): style (redundantCondition): Redundant condition: If decoded >= 9218868437227405313, the comparison decoded <= 9223372036854775807 is always true.
src/ua_types_encoding_binary.c(262): style (clarifyCalculation): Clarify calculation precedence for '&' and '?'.
src/ua_types_encoding_binary.c(276): style (duplicateExpression): Same expression on both sides of '!='.
src/ua_types_encoding_binary.c(278): style (duplicateExpression): Same expression on both sides of '!='.
src/ua_types_encoding_binary.c(309): style (duplicateExpression): Same expression on both sides of '!='.
src/ua_types_encoding_binary.c(311): style (duplicateExpression): Same expression on both sides of '!='.